### ISSUE TITLE
Anomalie lorsque l'on souhaite ajouter une note de frais, aucune action après le clique

### ISSUE THREAD

**Issue by adrivall** [Eoxia/frais.pro#5]

**Comment by eoxia-alexandre** [comment]
Bonjour,

Peut être un problème de cache du navigateur.
Pouvez vous essayer un autre navigateur et si cela fonctionne. Utiliser la combinaison de touche "ctrl + F5" pour rafraîchir le cache du navigateur

Cdlt,
Alexandre

**Comment by adrivall** [comment]
Bonjour,

Non, ce n'est pas un problème de cache malheureusement, si je check la
console, j'ai une erreur ajax :

Monsite/wp-admin/admin-ajax.php 500 (Internal Server Error)

send                                   @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:4
ajax                                    @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:4
n.(anonymous function)     @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:4
window.eoxiaJS.request.send @ wpeo-assets.js?ver=1.0.0:1138
(anonymous)                      @ wpeo-assets.js?ver=1.0.0:208
(anonymous)                      @ wpeo-assets.js?ver=1.0.0:340
each                                   @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:2
each                                   @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:2
jQuery.fn.get_data              @ wpeo-assets.js?ver=1.0.0:321
window.eoxiaJS.action.execAttribute @ wpeo-assets.js?ver=1.0.0:206
dispatch                              @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:3
r.handle                               @
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:3

Bonne journée,
Adrien

*Adrien VALLEE*
Directeur de Projet
Youdemus, Agence web pragmatique
15 rue Ramey, 75018 Paris
06 12 15 83 71


Le 5 avril 2018 à 11:00, Alexandre Techer <notifications@github.com> a
écrit :

**Comment by eoxia-alexandre** [comment]
Re bonjour,

Pouvez vous nous indiquer la version de PHP, WordPress
Pouvez vous activer le [mode DEBUG](https://codex.wordpress.org/Debugging_in_WordPress) sur le site?
Avez vous accès aux logs d'erreur apache?

Cdlt,
Alexandre

**Comment by adrivall** [comment]
Rebonjour,

Alors la version de PHP est . 5.3

**Comment by adrivall** [comment]
Rebonjour,

Alors la version de PHP est 5.4 je crois

Oui voici l'erreur que j'ai : 
Fatal error: Class 'IntlDateFormatter' not found in /app/knowmore/wp-content/plugins/frais-pro/core/external/eo-framework/core/util/class-date-util.php on line 73

Merci,
Cordialement,
Adrien

**Comment by eoxia-jimmy** [comment]
Bonjour,

nous avons effectivement un problème au niveau de l'extension INTL disponible dans PECL http://php.net/manual/fr/intl.installation.php ce qui, en conclusion provoque cette fatal error.

Nous allons voir comment passer outre cette extension qui à priori n'est pas disponible sur tous les serveurs.

Je tag cette Issue en "bug".

A suivre.

**Comment by adrivall** [comment]
Bonjour Jimmy,

Super, merci pour l'info.
Bon courage.

Adrien
